name: 'Deploy para VPS'
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Build da aplicação'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"

            if [ -s "$NVM_DIR/nvm.sh" ]; then
              . "$NVM_DIR/nvm.sh"
            else
              echo "❌ NVM não encontrado"
              exit 1
            fi

            nvm use --lts

            APP_DIR="${{ secrets.APP_DIR }}"
            REPO_URL="${{ secrets.REPO_URL }}"

            echo "➡️ Acessando diretório da aplicação"
            cd "$APP_DIR"

            echo "➡️ Atualizando código"
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone "$REPO_URL" .
            fi

            echo "➡️ Instalando dependências"
            npm install

            echo "➡️ Build da aplicação"
            node ace build

            echo "➡️ Subindo aplicação com PM2"
            pm2 delete undead || true
            pm2 start ecosystem.config.cjs
            pm2 save
